### ISSUE TITLE
Crash in Vigilante 8: 2nd Offense Menu

### ISSUE THREAD

**Issue by loganmc10** [gonetz/GLideN64#1479]
I tested both Project64 and mupen64plus using the latest master.

If you select "Arcade" then select a map, it will crash at the "Select Player" screen.

Here is the backtrace from mupen64plus:

```
#0  0x00007fffeedf0a62 in XXH_read64 (memPtr=0x7fffef530000) at mupen64plus-GLideN64/GLideN64/src/xxHash/xxhash.c:556
#1  0x00007fffeedf0c58 in XXH_readLE64_align (align=XXH_unaligned, endian=XXH_littleEndian, ptr=0x7fffef530000) at mupen64plus-GLideN64/GLideN64/src/xxHash/xxhash.c:583
#2  XXH64_endian_align (align=XXH_unaligned, endian=XXH_littleEndian, seed=4294967295, len=1134919673, input=0x7fffef121d60 <TMEM>) at mupen64plus-GLideN64/GLideN64/src/xxHash/xxhash.c:645
#3  XXH64 (input=0x7fffef121d60 <TMEM>, len=1134919673, seed=4294967295) at mupen64plus-GLideN64/GLideN64/src/xxHash/xxhash.c:712
#4  0x00007fffeedeeb6b in CRC_Calculate (crc=4294967295, buffer=0x7fffef121d60 <TMEM>, count=1134919673) at mupen64plus-GLideN64/GLideN64/src/CRC_OPT.cpp:51
#5  0x00007fffeed89415 in _calculateCRC (_t=0, _params=..., _bytes=1134919673) at mupen64plus-GLideN64/GLideN64/src/Textures.cpp:1264
#6  0x00007fffeed8a434 in TextureCache::update (this=0x7fffef523560 <TextureCache::get()::cache>, _t=0) at mupen64plus-GLideN64/GLideN64/src/Textures.cpp:1526
#7  0x00007fffeed62f3e in GraphicsDrawer::_updateTextures (this=0x7fffef525710 <DisplayWindow::get()::video+1104>) at mupen64plus-GLideN64/GLideN64/src/GraphicsDrawer.cpp:541
#8  0x00007fffeed630c9 in GraphicsDrawer::_updateStates (this=0x7fffef525710 <DisplayWindow::get()::video+1104>, _drawingState=DrawingState::Triangle)
    at mupen64plus-GLideN64/GLideN64/src/GraphicsDrawer.cpp:573
#9  0x00007fffeed633bb in GraphicsDrawer::_prepareDrawTriangle (this=0x7fffef525710 <DisplayWindow::get()::video+1104>) at mupen64plus-GLideN64/GLideN64/src/GraphicsDrawer.cpp:630
#10 0x00007fffeed6351f in GraphicsDrawer::drawTriangles (this=0x7fffef525710 <DisplayWindow::get()::video+1104>) at mupen64plus-GLideN64/GLideN64/src/GraphicsDrawer.cpp:659
#11 0x00007fffeed6869f in gSPFlushTriangles () at mupen64plus-GLideN64/GLideN64/src/gSP.cpp:46
#12 0x00007fffeed687ed in gSP2Triangles (v00=9, v01=28, v02=127, flag0=0, v10=0, v11=0, v12=64, flag1=0) at mupen64plus-GLideN64/GLideN64/src/gSP.cpp:77
#13 0x00007fffeed4f0ea in F3DEX_Tri2 (w0=101923071, w1=128) at mupen64plus-GLideN64/GLideN64/src/F3DEX.cpp:35
#14 0x00007fffeed7bcf8 in RSP_ProcessDList () at mupen64plus-GLideN64/GLideN64/src/RSP.cpp:110
#15 0x00007fffeed9b817 in PluginAPI::ProcessDList (this=0x7fffef5247e8 <PluginAPI::get()::api>) at mupen64plus-GLideN64/GLideN64/src/common/CommonAPIImpl_common.cpp:160
#16 0x00007fffeed49ecb in ProcessDList () at mupen64plus-GLideN64/GLideN64/src/CommonPluginAPI.cpp:23
```

It looks like it is getting the wrong size for the textures, and it's attempting to do a CRC calculation on out-of-bounds memory.

**Comment by loganmc10** [comment]
Is there some sort of known maximum value for ```_bytes```? Something where we could do:

```if (_bytes > maxValue) _bytes = maxValue;``` to prevent a crash?

**Comment by gonetz** [comment]
1134919673 is obviously too much for texture size. It is necessary to find, how that value was obtained and fix the error. You suggestion to limit _bytes size is not a fix, it just an attempt to bypass the problem.

**Comment by loganmc10** [comment]
Fixed, there are other gfx glitches with the menu obviously, but no more crashing
