### ISSUE TITLE
SEGFAULT in linux when attempting to create log file without directory permissions

### ISSUE THREAD

**Issue by dankcushions** [gonetz/GLideN64#930]
https://github.com/gonetz/GLideN64/commit/438f5e327b94302b97493c4cf84130ca265bcc58 forces a Warning to be logged, which seem to create a logfile by default: https://github.com/gonetz/GLideN64/blob/438f5e327b94302b97493c4cf84130ca265bcc58/src/Log.h#L11

That's fine, but it seems that if the directory the plugin is located does not have the correct permissions, we get a segfault. Here is a trace:
````
pi@retropie:/opt/retropie/emulators/mupen64plus/lib/mupen64plus $ gdb --args /opt/retropie/emulators/mupen64plus/bin/mupen64plus --noosd --fullscreen --gfx mupen64plus-video-GLideN64.so --configdir "/opt/retropie/configs/n64" --datadir "/opt/retropie/configs/n64" "/home/pi/RetroPie/roms/n64/Super Mario 64 (USA).n64"
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/retropie/emulators/mupen64plus/bin/mupen64plus...(no debugging symbols found)...done.
(gdb) tty /dev/tty1
(gdb) run
Starting program: /opt/retropie/emulators/mupen64plus/bin/mupen64plus --noosd --fullscreen --gfx mupen64plus-video-GLideN64.so --configdir /opt/retropie/configs/n64 --datadir /opt/retropie/configs/n64 /home/pi/RetroPie/roms/n64/Super\ Mario\ 64\ \(USA\).n64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x7268b460 (LWP 4949)]
[New Thread 0x70e89460 (LWP 4950)]
[New Thread 0x704ff460 (LWP 4951)]
[New Thread 0x6fcff460 (LWP 4952)]
[New Thread 0x6f4ff460 (LWP 4953)]

Program received signal SIGSEGV, Segmentation fault.
_IO_vfprintf_internal (s=0x0, 
    format=0x71a4b1b0 "N64 depth compare and depth based fog will not work without Image Textures support provided in OpenGL >= 4.3 or GLES >= 3.1", ap=...)
    at vfprintf.c:1278
1278    vfprintf.c: No such file or directory.
(gdb) bt
#0  _IO_vfprintf_internal (s=0x0, 
    format=0x71a4b1b0 "N64 depth compare and depth based fog will not work without Image Textures support provided in OpenGL >= 4.3 or GLES >= 3.1", ap=...)
    at vfprintf.c:1278
#1  0x7197bdb8 in LOG(unsigned short, char const*, ...) ()
   from ./mupen64plus-video-GLideN64.so
#2  0x7198a9c8 in OGLRender::_initExtensions() ()
   from ./mupen64plus-video-GLideN64.so
#3  0x7198b10c in OGLRender::_initData() () from ./mupen64plus-video-GLideN64.so
#4  0x7198b1f4 in OGLVideo::start() () from ./mupen64plus-video-GLideN64.so
#5  0x719965c8 in RomOpen () from ./mupen64plus-video-GLideN64.so
Cannot access memory at address 0x800000
#6  0x72868bb8 in ?? ()
   from /opt/retropie/emulators/mupen64plus/lib/libmupen64plus.so.2
Cannot access memory at address 0x800000
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
````
If you give the directory full permissions, the log is generated and everything works fine, but it should handle this scenario really.

It seems that https://github.com/gonetz/GLideN64/blob/438f5e327b94302b97493c4cf84130ca265bcc58/src/Log.h#L29 should check it has permissions before attempting to write the file.

**Comment by joolswills** [comment]
@dankcushions just needs a simple check like this I guess https://github.com/gonetz/GLideN64/pull/931

**Comment by gonetz** [comment]
Should be fixed with @joolswills patch:
https://github.com/gonetz/GLideN64/commit/dc23dc6be7862c57f39e1ed7197ff2ebff39625b

**Comment by dankcushions** [comment]
Solved! Thanks @joolswills 

This should have fixed the intial issue in https://github.com/gonetz/GLideN64/issues/497 also
